module: DragSelectCollectionView
author: "Haskel Ash"
author_url: https://haskelash.github.io
github_url: https://github.com/haskelash/DragSelectCollectionView
theme: fullwidth
documentation: Setup.md
readme: Setup.md
