language: swift
os: osx
osx_image: xcode9
script:
  - xcodebuild test -scheme DragSelectCollectionView -destination "name=iPhone 8,OS=11.0" CODE_SIGNING_REQUIRED=NO
after_success:
  - sudo gem install jazzy
  - jazzy
  - mkdir gh-pages
  - mv docs gh-pages/
  - mv gifs gh-pages/
  - mv README.md gh-pages/
  - mv _config.yml gh-pages/
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: gh-pages/
  on:
    branch: master
env:
  global:
  - secure: WgqmOE1fssBitrvG2l3LNf35urw2ME0HOIx/x83nwnnu4tO8wXAMcFROQC9j/Bn/Pg/1RLUMdJ7x7ehP/MfrU6xpwiJLPttOAxwV6CaFR+hTBumZcjF0RZ1wwWo/n+6f8vdubRuo5i6dBVwrDTlwum174oPJTumeGmIqSPihogJiwGD8s++WWKmOYcfQN148KKKpLiTvEE9ggIOl0fwQtZIERWCd6clMRqMHHcw4JVUrj0bXlp/E6URDaIw9Xv2ng4TprsiCipdAotVbJMD3b7eQ61u+CbcryR6wk91T6j9izcSyTLIl7HaOav1kxpktFIBDZPEB1FsaAYk253bypYGIMBH+d0H6DrsdCxr536Kv4Tx8wuC8Vho1QAKpTLw6wCiDECbe9dRoSDjWYE8aeY0g+bAJgHLQj8H6jsfkH6ApQQ71yAfGgi+HA0NeXlyI++CgiW32m+QB2I6LGpQiVgXlgrXjXQ2hiyqni3tAvvXDYTX+UnPZpTDEwSp8btiJoh4NLImWsMpePzyI8WkIHiHP+zzGZV2OHSI86h+iF3xeqOzS/yOy0qLOwswVa8T9HI8EaSPTl35Tp430j53yd9qjBBaLz+WVZWaAgpGZmw5YX/V+VDENJMzDPS1LGqftpBOHORqRaqKbSYty3CFG7zoLI4KbefnzJmpKavW6wko=
  - secure: lDb/2R2gqjVyIGzpB7cT9aD9ocgs2lAG5oWmhHmQRFVtA9S1E1kG2BRIRdJjkSy7yT1bm6GzO5A1UvdkgmvCZZaQkawygGJDwiMOk/V9kangLorMQddhSUU7R+4IRi1rRI1eoVGGBVGSxQyhrmsPG8BMDX0i1T4Rcloo6dHexLO5vPCEtyUGI8VBMAREt5KjWW+OJ6X/+LwFDIVI/z3LI8lgg8j2xxpok7IbewWQhnAfW0Xe6BXY8Ra+/961XtM1k3jeBLp67laMno6YdS8yDfwjZAJI+Y6lWEvRp5VdmxlBpyoUWvPpNG6aujA6X+KJbkv506Kh7yHXXYw4G/IOeMUe/Ne5Cve7vkHX31dY3+9aRysTzRZxkzn+ekhArDeEtslJK9nT8NatIzJ/2397pQAcbMvhKnYwTOJdNlSZN2M37VEjpRYQKezIM/Z6lrqiABNTrSGMKDDcVbr/tUtI6xEC9mGqgIJu916XQE9Li3MDXV5jD7dYy+lsyvXVTAkkSwsgn6LHe3+WwwMwSZIBR7NL3tQrtGE6ssaL21uG3rfZOuyGnfK5940R0rZ5rpazS/eL84ZTDUy4STX1zdLzGD7+HwP4csVIssejbSjJubqOHAemgjnsvEo+8RDCfL9ZzWjTGPi00xLAg1NtdZ2h/4RzsZnMGB9dY81ijpAd4Hk=
